parameters:
  - name: awsServiceConnectionName
    type: string 
  - name: awsVectoTfStateBucketName
    type: string
  - name: awsRegionName
    type: string
  - name: tfVersion
    type: string
    default: 1.6.0
  - name: directory
    type: string
    default: terraform

stages:
  - stage: TerraformPreparation
    displayName: "Terraform AWS-Side Preparation"
    jobs:
    - job: Preparation
      displayName: "Terraform Init, Validate & Plan"
      steps:
      - bash: |
          git version
          echo "Registering token for remote Git-Repos"
          echo "Length of REPO_ACCESS_1: ${#REPO_ACCESS_1}"
          git config --global --add url."https://${REPO_ACCESS_1}@github.com/acai-consulting/".insteadOf "https://github.com/acai-consulting/"
        displayName: "Preparint the Agent - Installing zip, unzip, registering tokens for ADO"
        env:
          REPO_ACCESS_1: $(GITHUB_PAT-ACCESS_1)

      - checkout: self
        persistCredentials: true

      - task: TerraformInstaller@1
        inputs:
          terraformVersion: ${{ parameters.tfVersion }}

      - task: AWSShellScript@1
        displayName: "Run Terraform Init & Validate"
        inputs:
          awsServiceConnectionName:  ${{ parameters.awsServiceConnectionName }}
          regionName: ${{ parameters.awsRegionName }}
          scriptType: "inline"
          inlineScript: |
            cd ${{parameters.directory}} 
            terraform init -backend-config="bucket=${{ parameters.awsVectoTfStateBucketName }}" -backend-config="region=${{ parameters.awsRegionName }}"
            terraform validate

      - script: |
          echo "Organization (Collection) ID: $(System.CollectionId)"
          # Extracting organization name from the URL
          ORG_NAME=$(echo "$(System.TeamFoundationCollectionUri)" | awk -F'/' '{print $(NF-1)}')  # Adjust if necessary
          cd ${{parameters.directory}}
          # Write the Terraform variables in HCL format
          cat > ado_settings.tfvars <<EOF
          vecto_setup_settings = {
            ado_settings = {
              organization_id = "$(System.CollectionId)"
              organization_name = "${ORG_NAME}"
              project_name = "$(System.TeamProject)"
              agent_pool_name = "${{ parameters.adoAgentPoolName }}"
            }
          }
          EOF
        displayName: 'Prepare ADO Settings for Terraform'


      - task: AWSShellScript@1
        displayName: "Run Terraform Plan"
        inputs:
          awsServiceConnectionName:  ${{ parameters.awsServiceConnectionName }}
          regionName: ${{ parameters.awsRegionName }}
          scriptType: "inline"
          continueOnError: false
          inlineScript: |
            cd ${{parameters.directory}} 
            export AZDO_PERSONAL_ACCESS_TOKEN=$(ADO_PAT-ADO_MANAGEMENT)

            terraform plan --var-file=ado_settings.tfvars --out=terraform.tfplan
            terraform show terraform.tfplan > terraform.tfplan.show
        env:
            ADO_PAT-ADO_MANAGEMENT: $(ADO_PAT-ADO_MANAGEMENT)
    
      - task: PublishPipelineArtifact@1 
        displayName: Publish artefact terraform.tfplan.show
        inputs: 
          targetPath: '${{ parameters.directory }}/terraform.tfplan.show' 
          artifactName: 'terraform.tfplan.show'

      - bash: |
          cd $(System.DefaultWorkingDirectory)
          zip -r terraform_folder.zip ./${{ parameters.directory }}/
          ls
        displayName: Zip terraform folder

      - task: PublishPipelineArtifact@1 
        displayName: Publish artefact terraform_folder.zip
        inputs: 
          targetPath: 'terraform_folder.zip' 
          artifactName: 'terraform_folder.zip'
